# Vagrantfile
# -*- mode: ruby -*-
# vi: set ft=ruby :


#/**
# *　　　　 ┏┓　　 　┏┓+ +
# *　　　　┏┛┻━━━━━━━┛┻━━┓　 + +
# *　　　　┃　　　　　　 ┃ 　
# *　　　　┃━　　━　　 　┃ ++ + + +
# *　　　 ████━████      ┃+
# *　　　　┃　　　　　　 ┃ +
# *　　　　┃　┻　　　    ┃
# *　　　　┃　　　　　　 ┃ + +
# *　　　　┗━━━┓　　 　┏━┛
# *　　　　　　┃　　 　┃　　　　　　　　　　　
# *　　　　　　┃　　 　┃ + + + +
# *　　　　　　┃　　 　┃　　　　Code is far away from bug 
# *　　　　　　┃　　 　┃　　　　with the animal protecting　　　　　　　
# *　　　　　　┃　　 　┃
# *　　　　　　┃　　 　┃ + 　　　　神兽保佑,代码无bug　　
# *　　　　　　┃　　 　┃
# *　　　　　　┃　　 　┃　　+　　　　　　　　　
# *　　　　　　┃　 　　┗━━━━━━━┓ + +
# *　　　　　　┃ 　　　　　　　┣┓
# *　　　　　　┃ 　　　　　　　┏┛
# *　　　　　　┗━━┓┓┏━━━━━┳┓┏━━┛ + + + +
# *　　　　　　　 ┃┫┫　   ┃┫┫
# *　　　　　　　 ┗┻┛　   ┗┻┛+ + + +
# */

# 创建5个节点的集群
# Usage: vagrant -f Vagrantfile.5nodes up

hosts = {
    "host01" => "192.168.11.101",
    "host02" => "192.168.11.102",
    "host03" => "192.168.11.103",
    "host04" => "192.168.11.104",
    "host05" => "192.168.11.105",
}

Vagrant.configure("2") do |config|
    hosts.each do |name, ip|
        config.vm.define name do |machine|
            machine.vm.box = "node-base"
            machine.vm.box_check_update = false
            machine.ssh.insert_key = false
            #machine.ssh.username = "vagrant"
            #machine.ssh.password = "vagrant"
            machine.vm.hostname = name
            machine.vm.network :private_network, ip: ip
            machine.vm.synced_folder ".", "/home/vagrant", disabled: false
            machine.vm.synced_folder "../../../", "/home/vagrant/sandbox", disabled: false
            machine.vm.provider "virtualbox" do |v|
                v.name = name
                v.customize ["modifyvm", :id, "--memory", 2048]
            end
        end                        
    end
end


